{{- if .Values.snapshotAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openbao.snapshotAgent.serviceAccount.name" . }}
  namespace: {{ include "openbao.namespace" . }}
  labels:
    helm.sh/chart: {{ include "openbao.chart" . }}
    app.kubernetes.io/name: {{ include "openbao.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if  .Values.snapshotAgent.serviceAccount.extraLabels -}}
      {{- toYaml .Values.snapshotAgent.serviceAccount.extraLabels | nindent 4 -}}
    {{- end -}}
  {{ template "openbao.snapshotAgent.serviceAccount.annotations" . }}
{{ end }}
