# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: openbao
version: 0.23.3
appVersion: v2.4.4
kubeVersion: ">= 1.30.0-0"
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://raw.githubusercontent.com/openbao/artwork/refs/heads/main/color/openbao-color.svg
keywords:
  [
    "vault",
    "openbao",
    "security",
    "encryption",
    "secrets",
    "management",
    "automation",
    "infrastructure",
  ]
sources:
  - https://github.com/openbao/openbao-helm
annotations:
  charts.openshift.io/name: Openbao
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: security
      description: |
        fix(deps): switch injector to openbao-k8s with patched golang.org/x/crypto (CVE-2024-45337)

maintainers:
  - name: OpenBao
    email: openbao-security@lists.openssf.org
    url: https://openbao.org
