# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: openbao
version: 0.19.2
appVersion: v2.4.3
kubeVersion: ">= 1.30.0-0"
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://github.com/openbao/artwork/blob/main/color/openbao-color.svg
keywords:
  [
    "vault",
    "openbao",
    "security",
    "encryption",
    "secrets",
    "management",
    "automation",
    "infrastructure",
  ]
sources:
  - https://github.com/openbao/openbao-helm
annotations:
  charts.openshift.io/name: Openbao
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: fixed
      description: |
        fix: grafana dashboard
    - kind: changed
      description: |
        chore: update OpenBao to 2.4.3
      links:
        - name: OpenBao 2.4.3 Release
          url: https://github.com/openbao/openbao/releases/tag/v2.4.3

maintainers:
  - name: OpenBao
    email: openbao-security@lists.openssf.org
    url: https://openbao.org
