name: Acceptance Tests
on: [push, workflow_dispatch, pull_request]
jobs:
  kind:
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version: [1.32.8, 1.33.4, 1.34.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup test tools
        uses: ./.github/actions/setup-test-tools
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          config: test/kind/config.yaml
          node_image: kindest/node:v${{ matrix.kind-k8s-version }}
          version: v0.29.0
      - name: Install Gateway API resources
        run: |
          kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml
      - name: Deploy LocalStack on Kind
        run: |
          helm repo add localstack-repo https://helm.localstack.cloud
          helm upgrade localstack -n localstack --create-namespace --install --version=0.6.27 localstack-repo/localstack
      - run: bats --tap --timing ./test/acceptance
permissions:
  contents: read
